/* GAMES */
CREATE TABLE table_name(
GAME_DATE_EST VARCHAR(100),
GAME_ID DOUBLE,
GAME_STATUS_TEXT VARCHAR(100),
HOME_TEAM_ID DOUBLE,
VISITOR_TEAM_ID DOUBLE,
SEASON DOUBLE,
TEAM_ID_home DOUBLE,
PTS_home DOUBLE,
FG_PCT_home DOUBLE,
FT_PCT_home DOUBLE,
FG3_PCT_home DOUBLE,
AST_home DOUBLE,
REB_home DOUBLE,
TEAM_ID_away DOUBLE,
PTS_away DOUBLE,
FG_PCT_away DOUBLE,
FT_PCT_away DOUBLE,
FG3_PCT_away DOUBLE,
AST_away DOUBLE,
REB_away DOUBLE,
HOME_TEAM_WINS DOUBLE
);

/* GAMES DETAILS */
CREATE TABLE table_name(
GAME_ID DOUBLE,
TEAM_ID DOUBLE,
TEAM_ABBREVIATION VARCHAR(100),
TEAM_CITY VARCHAR(100),
PLAYER_ID DOUBLE,
PLAYER_NAME VARCHAR(100),
START_POSITION VARCHAR(100),
COMMENT VARCHAR(100),
MIN VARCHAR(100),
FGM DOUBLE,
FGA DOUBLE,
FG_PCT DOUBLE,
FG3M DOUBLE,
FG3A DOUBLE,
FG3_PCT DOUBLE,
FTM DOUBLE,
FTA DOUBLE,
FT_PCT DOUBLE,
OREB DOUBLE,
DREB DOUBLE,
REB DOUBLE,
AST DOUBLE,
STL DOUBLE,
BLK DOUBLE,
T_O DOUBLE,
PF DOUBLE,
PTS DOUBLE,
PLUS_MINUS VARCHAR(100)
);
/* PLAYERS */
CREATE TABLE table_name(
PLAYER_NAME VARCHAR(100),
TEAM_ID DOUBLE,
PLAYER_ID DOUBLE,
SEASON DOUBLE
);
/* RANKINGS */
CREATE TABLE table_name(
TEAM_ID DOUBLE,
LEAGUE_ID DOUBLE,
SEASON_ID DOUBLE,
STANDINGSDATE VARCHAR(100),
CONFERENCE VARCHAR(100),
TEAM VARCHAR(100),
G DOUBLE,
W DOUBLE,
L DOUBLE,
W_PCT DOUBLE,
HOME_RECORD VARCHAR(100),
ROAD_RECORD VARCHAR(100)
);
/* TEAMS */
CREATE TABLE table_name(
LEAGUE_ID DOUBLE,
TEAM_ID DOUBLE,
MIN_YEAR DOUBLE,
MAX_YEAR DOUBLE,
ABBREVIATION VARCHAR(100),
NICKNAME VARCHAR(100),
YEARFOUNDED DOUBLE,
CITY VARCHAR(100),
ARENA VARCHAR(100),
ARENACAPACITY DOUBLE,
OWNER VARCHAR(100),
GENERALMANAGER VARCHAR(100),
HEADCOACH VARCHAR(100),
DLEAGUEAFFILIATION VARCHAR(100)
);
